autocomplete = false
breaking_changes = true
issues = true
emoji = false
sign = false

[[commit_types]]
name = "feat"
emoji = "âœ¨"
description = "A new feature"

[[commit_types]]
name = "fix"
emoji = "ğŸ›"
description = "A bug fix"

[[commit_types]]
name = "docs"
emoji = "ğŸ“š"
description = "Documentation only changes"

[[commit_types]]
name = "wip"
emoji = "ğŸ‘·"
description = "Do not create PR with this commit"
